import assert from 'node:assert/strict';
import {webcrypto,createHmac} from 'node:crypto';
import {validSignature,parseWhatsApp} from '../convex/whatsappPayload.ts';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const phone='5511999999999',id='business-id',secret='test-secret';
const payload={object:'whatsapp_business_account',entry:[{changes:[{field:'messages',value:{metadata:{phone_number_id:id},messages:[{id:'wamid.test',from:phone,timestamp:'1791280800',type:'text',text:{body:'Gastei 12,34 em alimentação'}}]}}]}]};
const raw=JSON.stringify(payload),signature='sha256='+createHmac('sha256',secret).update(raw).digest('hex');
assert(await validSignature(raw,signature,secret));
assert.equal(await validSignature(raw+' ',signature,secret),false);
assert.equal(await validSignature(raw,signature,'wrong'),false);
assert.equal(await validSignature(raw,'sha256=00',secret),false);
assert.equal(parseWhatsApp(payload,phone,id).length,1);
assert.equal(parseWhatsApp(payload,'different',id).length,0);
assert.equal(parseWhatsApp(payload,phone,'different').length,0);
assert.equal(parseWhatsApp(null,phone,id).length,0);
assert.deepEqual(parseWhatsApp({object:'whatsapp_business_account',entry:[null,{changes:[null,{field:'messages',value:{metadata:{phone_number_id:id},messages:[null]}}]}]},phone,id),[]);
const message=payload.entry[0].changes[0].value.messages[0];
message.type='image';assert.equal(parseWhatsApp(payload,phone,id).length,0);
message.type='text';message.text.body='x'.repeat(4001);assert.equal(parseWhatsApp(payload,phone,id).length,0);
message.text.body='valid';message.timestamp='invalid';assert.equal(parseWhatsApp(payload,phone,id).length,0);
console.log('PASS WhatsApp HMAC, tampering, sender/recipient isolation, text only, payload limits and invalid timestamps');
