/* V10 FinanceStore — production real state with self-healing baseline */
(()=>{'use strict';const KEY='meu_assessor_financeiro_v10_real',LEGACY='assessor_v180_simulacao_ficticia',SCHEMA=4,clone=x=>JSON.parse(JSON.stringify(x)),arrays=['accounts','cards','transactions','recurring','investments','invoices','budgets','goals'];
function clean(s){s=s&&typeof s==='object'?clone(s):{};arrays.forEach(k=>s[k]=Array.isArray(s[k])?s[k]:[]);s.accounts=s.accounts.filter(a=>!/nubank|btg/i.test(String(a.name||'')));s.transactions=s.transactions.filter(t=>!/(demo|fict[ií]ci|simula[cç][aã]o)/i.test([t.source,t.origin,t.desc].join(' ')));s.meta={...(s.meta||{}),schemaVersion:SCHEMA,environment:'production',dataMode:'real'};return s}
function valid(s){return !!(s&&s.meta?.schemaVersion===SCHEMA&&s.meta?.environment==='production'&&s.meta?.dataMode==='real'&&Array.isArray(s.transactions))}
const up=(a,x)=>{const i=a.findIndex(y=>y.id===x.id);i<0?a.push(x):a[i]={...a[i],...x}};
function baseline(s){s=clean(s);
 up(s.accounts,{id:'acc_c6',name:'C6 Bank',type:'Conta corrente',balance:1103.67,openingBalance:34.31,balanceDate:'2026-09-18',source:'real-user-data'});up(s.accounts,{id:'acc_itau',name:'Itaú',type:'Conta corrente',balance:0,balanceUnknown:true});up(s.accounts,{id:'acc_xp',name:'Banco XP',type:'Conta corrente',balance:0,balanceUnknown:true});
 up(s.cards,{id:'card_c6_carbon',name:'C6 Bank Carbon',bank:'C6 Bank',type:'Crédito',limit:0});up(s.cards,{id:'card_caju_alimentacao',name:'Caju Alimentação',bank:'Caju',type:'Benefício',category:'Alimentação',limit:1500,balance:881.95,availableLimit:881.95,excludeFromPatrimony:true});
 const tx=[['c6_pix','2026-09-10','Pix recebido','Transferências','',304.57,true],['c6_recarga','2026-09-10','RECARGA CELULAR','Comunicação','',-20,false],['c6_estorno','2026-09-10','EST RECARGA DE CEL','Estornos','',20,true],['c6_super','2026-09-11','SUPER NORTE','Alimentação','',-79.05,false],['c6_fm','2026-09-11','FM AGENCIAMENTO','Outros','',-14.85,false],['c6_deb','2026-09-11','Débito de cartão','Outros','',-71.50,false],['c6_drog','2026-09-11','Drogaria','Saúde','',-12.99,false],['c6_lav1','2026-09-12','LAVLAND.JP','Serviços','',-19.89,false],['c6_lav2','2026-09-12','LAVLAND.JP','Serviços','',-19.90,false],['c6_nexa','2026-09-13','NEXA INTERMEDIAÇÕES','Outros','',-24.99,false],['c6_jm1','2026-09-14','J.M.COM','Outros','',-2.50,false],['c6_posto','2026-09-15','AutoPostoJardim','Transporte','',-30,false],['c6_jm2','2026-09-15','J.M.COM','Outros','',-4,false]];
 tx.forEach(x=>up(s.transactions,{id:x[0],date:x[1],desc:x[2],cat:x[3],sub:x[4],value:x[5],status:'posted',source:'C6 Bank statement',accountId:'acc_c6',excludeFromExpense:x[6]}));
 [['caju_2026_09_17_padaria_1','2026-09-17','19:34','Padaria e Confeit',-1],['caju_2026_09_17_padaria_14','2026-09-17','19:36','Padaria e Confeit',-14],['caju_2026_09_17_marilza_2999','2026-09-17','22:19','Ifd*60.939.734 Marilza Fa',-29.99],['caju_20260918_bakery_3090','2026-09-18','10:26','Bakery and Confectionery Real',-30.90],['caju_20260918_4905','2026-09-18','12:42','Compra Caju',-49.05]].forEach(x=>up(s.transactions,{id:x[0],date:x[1],time:x[2],desc:x[3],cat:'Alimentação',sub:'Padaria/Alimentação',value:x[4],status:'posted',source:'Caju',origin:'Caju Crédito',cardId:'card_caju_alimentacao',excludeFromPatrimony:true}));
 up(s.transactions,{id:'real_rescisao_20260918',date:'2026-09-18',desc:'Rescisão Contratual',cat:'Receitas',sub:'Rescisão',value:1069.36,status:'posted',source:'user-confirmed',accountId:'acc_c6'});
 up(s.transactions,{id:'sal_2026_10',date:'2026-10-01',desc:'Salário líquido outubro',cat:'Receitas',sub:'Salário',value:6500,status:'planned',source:'user-approved',accountId:'acc_c6'});
 for(let i=0;i<9;i++){const d=new Date(2026,10+i,1),k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');up(s.transactions,{id:'sal_'+k.replace('-','_'),date:k+'-01',desc:'Salário líquido estimado',cat:'Receitas',sub:'Salário',value:10104.50,status:'planned',source:'calculated-2026',accountId:'acc_c6'})}
 up(s.transactions,{id:'decimo_2026',date:'2026-12-20',desc:'13º proporcional estimado (4/12)',cat:'Receitas',sub:'13º',value:3893.44,status:'planned',source:'calculated-2026',accountId:'acc_c6',grossValue:4533.33});
 const rec=[['rec_pensao','Pensão alimentícia','Família',1500,'2027-07-10'],['rec_carro','Prestação do carro','Transporte',1000,'2027-07-10'],['rec_aluguel','Aluguel','Moradia',1250,'2027-07-10'],['rec_internet','Internet','Moradia',80,'2027-07-10'],['rec_tim','Plano TIM','Comunicação',79.90,'2027-07-10'],['rec_emp_mae','Empréstimo mãe','Empréstimos/Compromissos',300,'2027-05-10']];rec.forEach(x=>up(s.recurring,{id:x[0],desc:x[1],cat:x[2],value:-x[3],startDate:'2026-10-10',endDate:x[4],dueDay:10,frequency:'monthly',active:true,source:'user-approved'}));
 s.meta={...(s.meta||{}),schemaVersion:SCHEMA,environment:'production',dataMode:'real',realBaseline:'2026-09-18',cajuKnownBalance:881.95,cajuKnownBalanceAt:'2026-09-18T12:42:00-03:00'};return s}
function migrate(){let s;try{s=JSON.parse(localStorage.getItem(KEY)||'null')}catch(_){}if(!s){try{s=JSON.parse(localStorage.getItem(LEGACY)||'null')}catch(_){}}s=baseline(s);localStorage.setItem(KEY,JSON.stringify(s));return s}
let state=migrate(),listeners=new Set();function persist(reason='save'){state=baseline(state);localStorage.setItem(KEY,JSON.stringify(state));window.db=state;listeners.forEach(fn=>fn(state,reason));document.dispatchEvent(new CustomEvent('finance-store-changed',{detail:{reason}}));return state}
function get(){return state}function set(x,r='set'){state=clean(x);return persist(r)}function update(fn,r='update'){const d=clone(state);fn(d);return set(d,r)}function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}function upsertTx(tx){return update(s=>up(s.transactions,tx),'transaction')}
window.db=state;window.FinanceStoreV10={KEY,SCHEMA,get,set,update,subscribe,upsertTx,persist,valid,clean,baseline};document.dispatchEvent(new CustomEvent('finance-store-ready'));
})();