/* V10 FinanceEngine — canonical recurrence, investments and categories */
(()=>{'use strict';const n=v=>Number(v)||0,abs=v=>Math.abs(n(v)),key=v=>String(v||'').slice(0,7),norm=v=>String(v||'Outros').trim()||'Outros';
const planned=s=>/^(planned|planejada|planejado|prevista|previsto)$/i.test(String(s||''));const realized=s=>/^(posted|realized|realizada|realizado|confirmada|confirmado)$/i.test(String(s||''));
function recurringFor(state,k){return(state.recurring||[]).filter(r=>r.active!==false&&(!key(r.startDate)||k>=key(r.startDate))&&(!key(r.endDate)||k<=key(r.endDate)))}
function operational(state,k){return(state.transactions||[]).filter(t=>key(t.date)===k&&!t.transfer&&!t.excludeFromExpense)}
function summary(state,k){const op=operational(state,k);const realizedIncome=op.filter(t=>realized(t.status)&&n(t.value)>0).reduce((a,t)=>a+n(t.value),0),realizedExpense=op.filter(t=>realized(t.status)&&n(t.value)<0).reduce((a,t)=>a+abs(t.value),0),plannedIncome=op.filter(t=>planned(t.status)&&n(t.value)>0).reduce((a,t)=>a+n(t.value),0),direct=op.filter(t=>planned(t.status)&&n(t.value)<0).reduce((a,t)=>a+abs(t.value),0),rec=recurringFor(state,k).reduce((a,r)=>a+abs(r.value),0),investment=investmentPlanFor(state,k).reduce((a,t)=>a+abs(t.value),0);return{k,realizedIncome,realizedExpense,plannedIncome,plannedExpense:direct+rec,recurringExpense:rec,investment}}
function balances(state){const inv=a=>/invest/i.test(String(a.type||''));const usable=(state.accounts||[]).filter(a=>!a.excludeFromPatrimony);const liquid=usable.filter(a=>!inv(a)).reduce((a,x)=>a+n(x.balance),0),invest=usable.filter(inv).reduce((a,x)=>a+n(x.balance),0);return{liquid,invest,patrimony:liquid+invest}}
function investmentPlanFor(state,k){return(state.transactions||[]).filter(t=>key(t.date)===k&&t.transfer&&planned(t.status)&&String(t.destAccountId||t.dest)==='acc_invest_plan')}
function ensureInvestmentPlan(state){state.accounts=state.accounts||[];state.transactions=state.transactions||[];state.investments=state.investments||[];if(!state.accounts.some(a=>a.id==='acc_invest_plan'))state.accounts.push({id:'acc_invest_plan',name:'Investimentos',type:'Investimento',balance:0,openingBalance:0,source:'user-approved'});
 for(let i=0;i<9;i++){const d=new Date(2026,10+i,1),k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),id='aporte_'+k.replace('-','_');state.transactions=state.transactions.filter(t=>!(t.transfer&&key(t.date)===k&&String(t.destAccountId||t.dest)==='acc_invest_plan'&&t.id!==id));let t=state.transactions.find(x=>x.id===id);const v={id,date:k+'-10',desc:'Aporte mensal de investimento',cat:'Investimentos',sub:'Aporte mensal',value:-3000,status:'planned',source:'user-approved-investment-3000',accountId:'acc_c6',destAccountId:'acc_invest_plan',transfer:true,excludeFromExpense:true};t?Object.assign(t,v):state.transactions.push(v)}
 return state}
function categoryTotals(state,k,mode='auto'){const current=new Date().toISOString().slice(0,7),future=mode==='planned'||(mode==='auto'&&k>current),out={};const add=(cat,v)=>out[norm(cat)]=(out[norm(cat)]||0)+abs(v);
 operational(state,k).filter(t=>n(t.value)<0&&(future?planned(t.status):realized(t.status))).forEach(t=>add(t.cat,t.value));if(future)recurringFor(state,k).forEach(r=>add(r.cat,r.value));return Object.entries(out).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
function chartSeries(state,start='2026-10',count=12){return projection(state,start,count).map(r=>({month:r.k,income:r.plannedIncome,expense:r.plannedExpense,investment:r.investment,liquid:r.liquid,patrimony:r.patrimony,categories:categoryTotals(state,r.k,'planned')}))}
function projection(state,start='2026-10',count=12){let b=balances(state),liq=b.liquid,iv=b.invest,pat=b.patrimony;const[y,m]=start.split('-').map(Number),rows=[];for(let i=0;i<count;i++){const d=new Date(y,m-1+i,1),k=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0'),s=summary(state,k);liq+=s.plannedIncome-s.plannedExpense-s.investment;iv+=s.investment;pat+=s.plannedIncome-s.plannedExpense;rows.push({...s,liquid:liq,invest:iv,patrimony:pat})}return rows}
window.FinanceEngineV10={recurringFor,summary,balances,projection,investmentPlanFor,ensureInvestmentPlan,categoryTotals,chartSeries};
if(window.FinanceStoreV10){FinanceStoreV10.update(s=>ensureInvestmentPlan(s),'canonical-investment-plan')}
})();