/* V10 Runtime UI — authoritative navigation, month filters, KPI and chart refresh */
(()=>{'use strict';const valid=k=>/^\d{4}-\d{2}$/.test(String(k||'')),br=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function state(){return FinanceStoreV10?.get?.()} function engine(){return window.FinanceEngineV10}
function go(view){const target=document.getElementById('view-'+view);if(!target)return false;document.querySelectorAll('.module').forEach(x=>x.classList.toggle('active',x===target));document.querySelectorAll('#nav button[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));document.getElementById('sidebar')?.classList.remove('open');document.getElementById('overlay')?.classList.remove('show');scrollTo(0,0);window.RenderControllerV10?.schedule('nav:'+view);return true}
function setMonth(k){if(!valid(k))return false;window.activeMonth=k;localStorage.setItem('assessor_active_month',k);if(window.monthScopes)Object.keys(window.monthScopes).forEach(x=>window.monthScopes[x]=k);document.querySelectorAll('select.month-filter').forEach(s=>{if([...s.options].some(o=>o.value===k))s.value=k});window.RenderControllerV10?.schedule('month:'+k);return true}
function renderKpis(){const s=state(),E=engine(),box=document.getElementById('kpis');if(!s||!E||!box)return;const k=window.activeMonth||'2026-09',x=E.summary(s,k),b=E.balances(s),future=k>new Date().toISOString().slice(0,7);const data=[['PATRIMÔNIO TOTAL',b.patrimony,'accounts'],['DISPONÍVEL HOJE',b.liquid,'accounts'],['RECEITAS REALIZADAS',x.realizedIncome,'transactions'],['RECEITAS PREVISTAS',x.plannedIncome,'transactions'],['DESPESAS REALIZADAS',x.realizedExpense,'transactions'],['DESPESAS PREVISTAS',x.plannedExpense,'recurring'],['INVESTIMENTOS',b.invest,'investments']];box.innerHTML=data.map(([l,v,r])=>'<div class="card kpi clickable-card" tabindex="0" data-v10-route="'+r+'"><div class="label">'+l+'</div><div class="value">'+br(v)+'</div><div class="trend neutral">'+k+(future?' · previsto':'')+'</div></div>').join('');box.querySelectorAll('[data-v10-route]').forEach(el=>{el.onclick=()=>go(el.dataset.v10Route);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')go(el.dataset.v10Route)}})}
function renderCategory(){const s=state(),E=engine(),canvas=document.getElementById('categoryChart'),legend=document.getElementById('categoryLegend');if(!s||!E||!canvas)return;const k=window.activeMonth||'2026-09',items=E.categoryTotals(s,k,'auto');if(typeof window.drawDonut==='function')window.drawDonut(canvas,items);if(legend)legend.innerHTML=items.length?items.map(x=>'<div class="legend-line" data-canonical-category="'+x.name+'"><span>'+x.name+'</span><b>'+br(x.value)+'</b></div>').join(''):'<div class="notice">Sem despesas neste mês.</div>'}
function renderProjection(){const s=state(),E=engine();if(!s||!E)return;const n=Number(document.getElementById('periodProjection')?.value||12),rows=E.projection(s,window.activeMonth||'2026-09',n);if(typeof window.drawLineChart==='function'){window.drawLineChart(document.getElementById('projectionChart'),[{name:'Patrimônio projetado',data:rows.map(x=>x.patrimony),color:'#20d8ff'}],rows.map(x=>x.label))}const last=rows.at(-1),b=E.balances(s),h=document.getElementById('projectionHighlights');if(h&&last)h.innerHTML='<div class="projection-highlight"><small>Patrimônio atual</small><b>'+br(b.patrimony)+'</b></div><div class="projection-highlight"><small>Patrimônio projetado</small><b>'+br(last.patrimony)+'</b></div><div class="projection-highlight"><small>Custos no período</small><b>'+br(last.costs)+'</b></div><div class="projection-highlight"><small>Investimentos projetados</small><b>'+br(last.invest)+'</b></div>'}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('#nav button[data-view],[data-v10-route]');if(b){e.preventDefault();e.stopPropagation();go(b.dataset.view||b.dataset.v10Route)}},true);document.addEventListener('change',e=>{if(e.target.matches('select.month-filter')){e.stopImmediatePropagation();setMonth(e.target.value)}},true);document.getElementById('menuBtn')?.addEventListener('click',()=>{document.getElementById('sidebar')?.classList.toggle('open');document.getElementById('overlay')?.classList.toggle('show')},true);renderKpis();renderCategory();renderProjection()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();document.addEventListener('finance-store-changed',()=>window.RenderControllerV10?.schedule('store-ui'));window.RuntimeUIV10={go,setMonth,renderKpis,renderCategory,renderProjection};
})();