const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const sources = [
  'finance-store.js', 'finance-engine.js', 'cloud-sync.js', 'ai-gateway.js', 'mobile-theme.js',
  'mobile-dashboard.js', 'render-controller.js', 'month-sync.js', 'runtime-ui.js', 'experience.js', 'financial-cards.js',
  'finance-tests.js', 'ai-tests.js', 'diagnostics.js', 'health.js', 'test-21-30.js', 'tests.js',
  'acceptance-40-50.js', 'master-acceptance.js',
];
const banner = '/* Meu Assessor Financeiro V10 production bundle — generated by tools/build-v10.cjs */\n';
const body = sources.map((name) => `\n/* source: v10/${name} */\n${fs.readFileSync(path.join(root, 'v10', name), 'utf8').trim()}\n`).join('');
const footer = `\nwindow.V10App={version:'10.0.0',release:'v10-consolidacao',runAcceptance:()=>window.V10MasterAcceptance?.run?.()};\nwindow.dispatchEvent(new CustomEvent('v10-app-ready',{detail:{version:'10.0.0',release:'v10-consolidacao'}}));\n`;
fs.writeFileSync(path.join(root, 'v10', 'app.bundle.js'), banner + body + footer);
console.log(`Built v10/app.bundle.js from ${sources.length} ordered modules.`);
